# Generated by Django 4.0.3 on 2022-03-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
