# Generated by Django 4.0.3 on 2022-04-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='aboutBussiness_proposal',
            new_name='about_bussiness_proposal',
        ),
    ]
