# Generated by Django 4.0.3 on 2022-04-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_applicationform_about_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='company_logo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
