# Generated by Django 4.0.3 on 2022-04-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_applicationform_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
