# Generated by Django 4.0.3 on 2022-04-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_applicationform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
