# Generated by Django 4.0.3 on 2022-04-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_applicationform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='slot_booked',
            field=models.BooleanField(default=False),
        ),
    ]
