# Generated by Django 4.0.3 on 2022-04-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_applicationform_slot_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.applicationform')),
            ],
        ),
    ]
