# Generated by Django 4.0.3 on 2022-04-04 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_mainslotbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainslotbooking',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.applicationform'),
        ),
    ]
