# Generated by Django 4.0.3 on 2022-04-04 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_mainslotbooking_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondarySlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.applicationform')),
            ],
        ),
    ]
