# Generated by Django 4.0.3 on 2022-04-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_applicationform_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='company_logo',
        ),
    ]
