# Generated by Django 4.0.3 on 2022-04-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_company_mainslotbooking_application_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylogo',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
